# Project Information
site_name:              OASIS Documentation
site_description:       A VR Game
site_author:            Elemental 9 & Richie Bendall

# Repository
repo_name:              elemental9/OASIS
repo_url:               https://github.com/elemental9/OASIS
edit_uri:               ""

# Copyright
copyright:              'Copyright &copy; 2018 Elemental 9 & Richie Bendall'

# Page Tree
nav:
    - Home:             index.md
